#ifndef RESOURCE_H
#define RESOURCE_H

// App Icon
#define IDI_APPICON 101

// Timer IDs
#define IDT_TIMER_CHECK_IDLE 2001
#define IDT_TIMER_CHECK_TIMED_SHUTDOWN 2002
#define IDT_TIMER_SHUTDOWN_COUNTDOWN 2003

// GUI Control IDs
#define IDC_CHK_AUTORUN             100
#define IDC_CHK_TIMED_SHUTDOWN      101
#define IDC_EDIT_SHUTDOWN_HOUR      102
#define IDC_EDIT_SHUTDOWN_MINUTE    103
#define IDC_CHK_IDLE_SHUTDOWN       104
#define IDC_EDIT_IDLE_MINUTES       105
#define IDC_EDIT_COUNTDOWN_SECONDS  106
#define IDC_CHK_HIDE_MAIN_WINDOW    108
#define IDC_BTN_SAVE_SETTINGS       109
#define IDC_BTN_SHUTDOWN_NOW        110
#define IDC_BTN_EXIT_APP            112
#define IDC_BTN_HIDE_PROGRAM        113

#endif // RESOURCE_H
